# Generated by Django 5.1.1 on 2024-09-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_key', models.CharField(max_length=100)),
                ('license_type', models.CharField(max_length=100)),
                ('license_status', models.CharField(max_length=100)),
                ('license_expiry', models.CharField(max_length=100)),
                ('connection_limit', models.IntegerField()),
                ('payment_system', models.CharField(max_length=100)),
            ],
        ),
    ]
